### ISSUE TITLE
Styling for buttons not working

### ISSUE THREAD

**Issue by khenrix** [scania/corporate-ui-angular#1]
Styling not working for buttons, I'm guessing that's on your to-do list or I'm doing something wrong.
Changing to `<c-theme name='scania' global="true"></c-theme>` does not seem to do anything.

![image](https://user-images.githubusercontent.com/14275222/58416563-5021b180-8082-11e9-8692-1c115bfbabc6.png)

I imported the bootstrap css with original styling for now.

![image](https://user-images.githubusercontent.com/14275222/58417055-ec988380-8083-11e9-9ca3-3b4e76fbe6ab.png)

**Comment by helloimela** [comment]
Hi @khenrix , yes this will be in the next release. We will have a new release soon in a few days :)
It is available in the master now. If you want to try now, you can clone the repository and do `npm pack` inside the cloned repository. Then you can install the package file into your project, for example:
```
npm i ../corporate-ui-dev/corporate-ui-dev-4.0.0-alpha.1.tgz
```

**Comment by khenrix** [comment]
Great! case closed then.
